### ISSUE TITLE
Connected But No internet!

### ISSUE THREAD

**Issue by einkaaf** [FranzKafkaYu/x-ui#154] opened 2022-11-05 08:43 UTC
Hi Franz , Thank you answering my question all time
There is new Problem , After I Updated version from @vaxilu to your X-Ui , Our IOS user that use shadowlink or napsternetV App
had connection problem below :
App Shows that Vpn(vmess) is Connected but No Websites or application is working !

this issue happens right after i upgrade vaxilu to your ui , Please Help Me to fix this issue
Thank you

**Comment by FranzKafkaYu** [comment] 2022-11-05 08:54
@einkaaf did you have tried shadowRocket yet?And did you have tried other client APP such as V2rayNG(Android)、V2rayN（Windows）？Maybe the problem is napsternetV  side.

**Comment by einkaaf** [comment] 2022-11-05 09:00
> @einkaaf did you have tried shadowRocket yet?And did you have tried other client APP such as V2rayNG(Android)、V2rayN（Windows）？Maybe the problem is napsternetV side.

yes I tried but there is same problem !
Android is completely Ok (also windows) and has perfect speed but iOS version is connected and has no internet connection !
Is There anything different between your version and vaxilu that makes this happen ?
Can I downgrade to vaxilu to fix this issue ? 

I don't have any idea about this ! :)

**Comment by FranzKafkaYu** [comment] 2022-11-05 09:25
> > @einkaaf did you have tried shadowRocket yet?And did you have tried other client APP such as V2rayNG(Android)、V2rayN（Windows）？Maybe the problem is napsternetV side.
> 
> yes I tried but there is same problem ! Android is completely Ok (also windows) and has perfect speed but iOS version is connected and has no internet connection ! Is There anything different between your version and vaxilu that makes this happen ? Can I downgrade to vaxilu to fix this issue ?
> 
> I don't have any idea about this ! :)

this problem has nothing to do with x-ui,the problem may be caused by xray core version,my x-ui will use the latest version 1.6.1 while the original one is 1.4.2

**Comment by einkaaf** [comment] 2022-11-05 09:39
> > > @einkaaf did you have tried shadowRocket yet?And did you have tried other client APP such as V2rayNG(Android)、V2rayN（Windows）？Maybe the problem is napsternetV side.
> > 
> > 
> > yes I tried but there is same problem ! Android is completely Ok (also windows) and has perfect speed but iOS version is connected and has no internet connection ! Is There anything different between your version and vaxilu that makes this happen ? Can I downgrade to vaxilu to fix this issue ?
> > I don't have any idea about this ! :)
> 
> this problem has nothing to do with x-ui,the problem may be caused by xray core version,my x-ui will use the latest version 1.6.1 while the original one is 1.4.2

Can I change version in your panel ? maybe this works !

**Comment by FranzKafkaYu** [comment] 2022-11-05 09:47
> > > > @einkaaf did you have tried shadowRocket yet?And did you have tried other client APP such as V2rayNG(Android)、V2rayN（Windows）？Maybe the problem is napsternetV side.
> > > 
> > > 
> > > yes I tried but there is same problem ! Android is completely Ok (also windows) and has perfect speed but iOS version is connected and has no internet connection ! Is There anything different between your version and vaxilu that makes this happen ? Can I downgrade to vaxilu to fix this issue ?
> > > I don't have any idea about this ! :)
> > 
> > 
> > this problem has nothing to do with x-ui,the problem may be caused by xray core version,my x-ui will use the latest version 1.6.1 while the original one is 1.4.2
> 
> Can I change version in your panel ? maybe this works !

of course you can,but you can't downgrade xray core version directly,you can download xray core binary(1.4.2 version) and put  it in /usr/local/x-ui/bin directory

**Comment by einkaaf** [comment] 2022-11-05 09:49
Ok , Let me try !

**Comment by einkaaf** [comment] 2022-11-05 09:49
> > > > > @einkaaf did you have tried shadowRocket yet?And did you have tried other client APP such as V2rayNG(Android)、V2rayN（Windows）？Maybe the problem is napsternetV side.
> > > > 
> > > > 
> > > > yes I tried but there is same problem ! Android is completely Ok (also windows) and has perfect speed but iOS version is connected and has no internet connection ! Is There anything different between your version and vaxilu that makes this happen ? Can I downgrade to vaxilu to fix this issue ?
> > > > I don't have any idea about this ! :)
> > > 
> > > 
> > > this problem has nothing to do with x-ui,the problem may be caused by xray core version,my x-ui will use the latest version 1.6.1 while the original one is 1.4.2
> > 
> > 
> > Can I change version in your panel ? maybe this works !
> 
> of course you can,but you can't downgrade xray core version directly,you can download xray core binary(1.4.2 version) and put it in /usr/local/x-ui/bin directory

Ok , Let me try !

**Comment by shiroosaeed** [comment] 2022-11-05 09:49
In iOS you can download 'fair vpn'
For fix this problem

**Comment by einkaaf** [comment] 2022-11-05 09:51
> In iOS you can download 'fair vpn' For fix this problem

I Try this But Problem is still exist ! :(

**Comment by FranzKafkaYu** [comment] 2022-11-05 10:07
> > In iOS you can download 'fair vpn' For fix this problem
> 
> I Try this But Problem is still exist ! :(

For security i suggest you use ShadowRocket.

**Comment by einkaaf** [comment] 2022-11-05 10:17
> > > In iOS you can download 'fair vpn' For fix this problem
> > 
> > 
> > I Try this But Problem is still exist ! :(
> 
> For security i suggest you use ShadowRocket.

it is 3$ , and we have payment problem in IR

**Comment by FranzKafkaYu** [comment] 2022-11-05 10:49
> > > > In iOS you can download 'fair vpn' For fix this problem
> > > 
> > > 
> > > I Try this But Problem is still exist ! :(
> > 
> > 
> > For security i suggest you use ShadowRocket.
> 
> it is 3$ , and we have payment problem in IR

it's your choice. old version may expose your server easily.And this issue has nothing to do with x-ui,so I will close this issue.

**Closed by FranzKafkaYu** 2022-11-05 10:49 UTC
